### ISSUE TITLE
 404 file not found error

### ISSUE THREAD

**Issue by fazeln** [jdevfullstack/github-pages-tutorial#8]
Hi I read your tutorial and tried different other tutotial to solve my  [404 file not found error while publishing source for my GitHub Pages site](https://github.community/t/404-file-not-found-error-while-publishing-source-for-my-github-pages-site/160281).

I created my page two years ago with no problem; however, I have been trying to update my pages and I am not sure what I am doing wrong getting this error.  https://fazeln.github.io/  my repo is https://github.com/fazeln/fazeln.github.io

Could you please help me

**Comment by jfullstackdev** [comment]
if you click this link, which is one file at the root of your GitHub Pages, it will download the file, meaning, it is already hosting,

https://fazeln.github.io/index.Rmd

but I don't know about your content, maybe you used another framework for that, so since the tutorial is about the GitHub Pages and it is already working, then you look at your content

also, take a look at this,

https://fazeln.github.io/content/blog/2021-01-16-health-disparity.en.html

as you can see, there is the page, so I really don't know what you are trying to achieve with folders inside folders, maybe it is the folder structure of your project
